### ISSUE TITLE
Clicking back button in browser takes 3 clicks before it works

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#62]
**Describe the bug**
If I want to go back to the previous page it won't work unless I click the browser back button three times

This is in chrome on a MacBook Pro High Sierra

**Comment by DanielJDufour** [comment]
I'll take this

**Comment by DanielJDufour** [comment]
Issue is most likely dispatching too many duplicative changes to the history.  Possible solution is to try to cut down on this and try to add in a check, so that don't call history method if previous history entry includes same data.

**Comment by DanielJDufour** [comment]
I figured out what the problem is.  It's that I'm updating the URL parameters event when there isn't a substantive change that affects what appears on the page.  For example, adding `sort=data_quality` to search results page won't impact anything because that's the default.  Solution is to push the longer url with all the params when I change routes programmatically.

**Comment by DanielJDufour** [comment]
Fixed
